In [5]:
import numpy as np
import pandas as pd

In [7]:
dataset = pd.read_csv( "Downloads/bank.csv")

In [8]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [9]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [10]:
m = dataset.iloc[:,0:9]
n = dataset.iloc[:,11:13]
o = dataset.iloc[:,14:16]

In [11]:
x = m.join(n)
x = x.join(o)

In [12]:
x = x.values
y = dataset.iloc[:,16:].values

In [13]:
x[0]

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown'], dtype=object)

In [14]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [16]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [17]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
y = ct1.fit_transform(y)

In [18]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [19]:
y[70]

array([0., 1.])

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
categorical = Sequential()

In [25]:
x_train.shape

(8929, 37)

In [26]:
y_train.shape

(8929, 2)

In [27]:
categorical.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [28]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [29]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [30]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [31]:
categorical.add(Dense( units= 2, kernel_initializer= "random_uniform", activation="softmax"))

In [32]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"])

In [33]:
categorical.fit(x_train, y_train, epochs = 350)

Epoch 1/350
8929/8929 [==============================] - 2s 237us/sample - loss: 0.4605 - acc: 0.7845
Epoch 2/350
8929/8929 [==============================] - 1s 115us/sample - loss: 0.4196 - acc: 0.8129
Epoch 3/350
8929/8929 [==============================] - 1s 113us/sample - loss: 0.4134 - acc: 0.8164
Epoch 4/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.4098 - acc: 0.8196
Epoch 5/350
8929/8929 [==============================] - 1s 114us/sample - loss: 0.4058 - acc: 0.8166
Epoch 6/350
8929/8929 [==============================] - 1s 113us/sample - loss: 0.4047 - acc: 0.8216
Epoch 7/350
8929/8929 [==============================] - 1s 102us/sample - loss: 0.4012 - acc: 0.8242
Epoch 8/350
8929/8929 [==============================] - 1s 88us/sample - loss: 0.3989 - acc: 0.8261
Epoch 9/350
8929/8929 [==============================] - 1s 96us/sample - loss: 0.3975 - acc: 0.8256
Epoch 10/350
8929/8929 [==============================] - 1s 106us/sample - loss: 0.

8929/8929 [==============================] - 1s 108us/sample - loss: 0.2576 - acc: 0.8995
Epoch 81/350
8929/8929 [==============================] - 1s 108us/sample - loss: 0.2497 - acc: 0.9045
Epoch 82/350
8929/8929 [==============================] - 1s 109us/sample - loss: 0.2519 - acc: 0.9031
Epoch 83/350
8929/8929 [==============================] - 1s 106us/sample - loss: 0.2487 - acc: 0.9037
Epoch 84/350
8929/8929 [==============================] - 1s 107us/sample - loss: 0.2478 - acc: 0.9032s - loss: 0.
Epoch 85/350
8929/8929 [==============================] - 1s 109us/sample - loss: 0.2446 - acc: 0.9030
Epoch 86/350
8929/8929 [==============================] - 1s 110us/sample - loss: 0.2440 - acc: 0.9056
Epoch 87/350
8929/8929 [==============================] - 1s 107us/sample - loss: 0.2434 - acc: 0.9066
Epoch 88/350
8929/8929 [==============================] - 1s 107us/sample - loss: 0.2416 - acc: 0.9077
Epoch 89/350
8929/8929 [==============================] - 1s 106us/sample 

8929/8929 [==============================] - 1s 90us/sample - loss: 0.1677 - acc: 0.9363
Epoch 159/350
8929/8929 [==============================] - 1s 80us/sample - loss: 0.1770 - acc: 0.9329
Epoch 160/350
8929/8929 [==============================] - 1s 95us/sample - loss: 0.1715 - acc: 0.9358
Epoch 161/350
8929/8929 [==============================] - 1s 101us/sample - loss: 0.1776 - acc: 0.9348
Epoch 162/350
8929/8929 [==============================] - 1s 107us/sample - loss: 0.1693 - acc: 0.9349
Epoch 163/350
8929/8929 [==============================] - 1s 105us/sample - loss: 0.1692 - acc: 0.9329
Epoch 164/350
8929/8929 [==============================] - 1s 108us/sample - loss: 0.1740 - acc: 0.9366
Epoch 165/350
8929/8929 [==============================] - 1s 110us/sample - loss: 0.1692 - acc: 0.9361
Epoch 166/350
8929/8929 [==============================] - 1s 109us/sample - loss: 0.1711 - acc: 0.9381
Epoch 167/350
8929/8929 [==============================] - 1s 111us/sample - loss

Epoch 237/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.1332 - acc: 0.9511
Epoch 238/350
8929/8929 [==============================] - 1s 111us/sample - loss: 0.1419 - acc: 0.9521
Epoch 239/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.1361 - acc: 0.9535
Epoch 240/350
8929/8929 [==============================] - 1s 108us/sample - loss: 0.1344 - acc: 0.9502
Epoch 241/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.1305 - acc: 0.9526
Epoch 242/350
8929/8929 [==============================] - 1s 91us/sample - loss: 0.1294 - acc: 0.9512
Epoch 243/350
8929/8929 [==============================] - 1s 78us/sample - loss: 0.1403 - acc: 0.9524
Epoch 244/350
8929/8929 [==============================] - 1s 91us/sample - loss: 0.1350 - acc: 0.9492
Epoch 245/350
8929/8929 [==============================] - 1s 99us/sample - loss: 0.1296 - acc: 0.9531
Epoch 246/350
8929/8929 [==============================] - 1s 112us/

8929/8929 [==============================] - 1s 108us/sample - loss: 0.1082 - acc: 0.9640
Epoch 316/350
8929/8929 [==============================] - 1s 111us/sample - loss: 0.1117 - acc: 0.9635
Epoch 317/350
8929/8929 [==============================] - 1s 111us/sample - loss: 0.1049 - acc: 0.9656
Epoch 318/350
8929/8929 [==============================] - 1s 109us/sample - loss: 0.1250 - acc: 0.9633
Epoch 319/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.1115 - acc: 0.9624
Epoch 320/350
8929/8929 [==============================] - 1s 110us/sample - loss: 0.0979 - acc: 0.9632
Epoch 321/350
8929/8929 [==============================] - 1s 111us/sample - loss: 0.0912 - acc: 0.9662
Epoch 322/350
8929/8929 [==============================] - 1s 112us/sample - loss: 0.1064 - acc: 0.9648
Epoch 323/350
8929/8929 [==============================] - 1s 110us/sample - loss: 0.1036 - acc: 0.9657
Epoch 324/350
8929/8929 [==============================] - 1s 110us/sample - l

In [34]:
ypred = categorical.predict(x_test)

In [36]:
ypred

array([[1.0000000e+00, 3.9117980e-25],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 4.1183332e-20],
       ...,
       [2.3964990e-02, 9.7603500e-01],
       [1.0000000e+00, 0.0000000e+00],
       [9.9492258e-01, 5.0774254e-03]], dtype=float32)

In [37]:
ypred = ypred>0.5

In [38]:
deposit = ["No","Yes"]
yp = categorical.predict(sc.transform(ct.transform([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown']])))
prediction = deposit[np.argmax(yp)]
prediction

'Yes'

In [39]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes